### ISSUE TITLE
/plot auto : Schematic is not loaded + NPE

### ISSUE THREAD

**Issue by KsenMih** [IntellectualSites/PlotSquared#1035]
**Debug paste link**:
I've got an error with _/plot debugpaste_ : http://pastebin.com/raw/pp2Bu9dF

**Description of the problem:**
When I use _/plot auto_, the schematic doesn't load.
When I use _/plot claim_, the schematic is loaded correctly.

**How to replicate**:

1. /plot auto with the "onclaim schematic feature" enabled.

**Versions**
PlotSquared version 3.4.0-SNAPSHOT
CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) Implementing API version 1.9-R0.1-SNAPSHOT

**Console Output** (after /plot auto)
http://pastebin.com/raw/2xdMe7H1

**Chat Output** (after /plot auto)
[Client thread/INFO]: [CHAT] An internal error occurred while attempting to perform this command
[Client thread/INFO]: [CHAT] [P2] You successfully claimed the plot
[Client thread/INFO]: [CHAT] [P2] You have been teleported

**Configuration**
http://pastebin.com/raw/Qa41GWLA

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
are you using the builds from the master branch or the 3.4.0 branch?

**Comment by KsenMih** [comment]
Sorry, I'm using the build #109 from http://ci.athion.net/job/PlotSquared/

I've also tested with the latest build, and previously, with the version available on Spigot.

**Comment by wasder** [comment]
Same here. Using `PlotSquared (Version: 3.4.0)` and `CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)`

**Comment by boy0001** [comment]
Can confirm error. Will fix soon.

**Comment by boy0001** [comment]
Fixed

**Comment by KsenMih** [comment]
Thanks a lot ! Good job.

**Comment by wasder** [comment]
Still having this issue. Using the latest build.
http://pastebin.com/raw/ZehKK6GE
