### ISSUE TITLE
/plot deny and remove survival inventory

### ISSUE THREAD

**Issue by aurel85** [IntellectualSites/PlotSquared#1638]
Hi,

When a player uses the /plot deny command to ban a player from his parcel and the banned player is tp on the parcel in question, it is obviously tp next to it. But when he returns to a survival world he completely lost his inventory. I have reproduced it at least 3 times.

I do not know if it's PlotSquared or PerWorldInventory that is causing a problem to see a conflict between the two but I prefer to report this bug which is quite annoying.

There is no error in the console :/

I am using PaperSpigot 1.11.2 and the last version of this plugin (3.5.0u2) and the same for PerWorldInventory (1.10.0).

**Comment by dordsor21** [comment]
does it happen without PerWorldInventory?

**Comment by aurel85** [comment]
Huuuum ... It's strange, on my test server that is in 1.12 I do not have this bug even with PerWorldInventory. My server will soon switch to 1.12 so I will tell you if the problem is still present.

**Comment by dordsor21** [comment]
possibly an issue that was fixed in PerWorldInventory then. I'll close for know, but let me know if it persists at some point here.

**Comment by aurel85** [comment]
The problem is still present even after my server is switched to 1.12. It's quite strange that I can not reproduce it on my test server. In the meantime, I blocked the / p deny & / p ban command.
