### ISSUE TITLE
Plot2Dynmap incompatibility with breaking changes.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2193]
Paper dev 488 (Spigot 1.13.2)
PlotSquared-Breaking dev 55
Plot2dynmap v3.4.0
dynmap version 3.0-SNAPSHOT-162

Would it be possible to update Plot2Dynmap to support the new PlotSquared 1.13 builds? :(

```
[04:51:04] [Server thread/ERROR]: Could not load 'plugins/Plot2Dynmap.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/object/RunnableVal
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:329) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/object/RunnableVal
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.13.2.jar:git-Paper-488]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.object.RunnableVal
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.13.2.jar:git-Paper-488]
	... 6 more
```

**Comment by Sauilitired** [comment]
I will fork it and put download links in our Discord. I don't have access to the repository, or the Spigot page.

**Comment by mibby** [comment]
Let me know if you need any assistance with testing!

**Comment by Sauilitired** [comment]
https://github.com/IntellectualSites/plot2dynmap/releases/tag/2
I've updated it. Please test it out and report back :smile:

**Comment by mibby** [comment]
@Sauilitired Seems to be working, thanks! I noticed one of the plots had ```Flags Flag { name='titles'}```, but that might just be a plots issue if it isn't functional yet.

**Comment by Sauilitired** [comment]
Ah, I think we changed how flags are serialized. I'll fix it.

**Comment by Sauilitired** [comment]
Fixed flag formatting in this release: https://github.com/IntellectualSites/plot2dynmap/releases/tag/2.1

**Comment by mibby** [comment]
@Sauilitired Using PlotSquared-breaking dev 78 and plot2dynmap v2.0.1, it's still broken. Not showing up on the live map.

```
[00:25:51] [Server thread/WARN]: java.lang.NullPointerException
[00:25:51] [Server thread/WARN]: 	at com.empcraft.plot2dynmap.Main.lambda$updatePlots$0(Main.java:193)
[00:25:51] [Server thread/WARN]: 	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
[00:25:51] [Server thread/WARN]: 	at java.base/java.util.TimSort.sort(TimSort.java:234)
[00:25:51] [Server thread/WARN]: 	at java.base/java.util.Arrays.sort(Arrays.java:1515)
[00:25:51] [Server thread/WARN]: 	at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
[00:25:51] [Server thread/WARN]: 	at com.empcraft.plot2dynmap.Main.updatePlots(Main.java:189)
[00:25:51] [Server thread/WARN]: 	at com.empcraft.plot2dynmap.Main.access$200(Main.java:38)
[00:25:51] [Server thread/WARN]: 	at com.empcraft.plot2dynmap.Main$Plot2Update.run(Main.java:413)
[00:25:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[00:25:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448)
[00:25:51] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
[00:25:51] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[00:25:51] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[00:25:51] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[00:25:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

As for someone named dustinhimpler owning 30,000 plots somehow even though I have permission limits, I just decided to purge him via console.

**Comment by TNTUP** [comment]
Seems not to work for me, sorry by replying on this closed issue. Should I make an issue on the Plot2Dynmap or here ?

**Comment by TNTUP** [comment]
Any news? Been a month I haven't got a reply and I still can't see who owns the plot from the dynmap

**Comment by TNTUP** [comment]
Not working in 1.14.4 on Paper with PlotSquared-Breaking 4.343 :(

**Comment by MattBDev** [comment]
@TNTUP You need to contact Empire92(Jesse) about this. We don't control Plot2Dynmap.

**Comment by TNTUP** [comment]
Been months since I've passed on 1.13.x and 1.14.x and no luck... Guessing the Plot2Dynmap addon is dead... Thanks for your answer Matt!

**Comment by MattBDev** [comment]
@TNTUP I'll look into updating the addon myself but don't count on it. I'm a bit stretched at the moment.
