### ISSUE TITLE
1.14 and 1.14.1 use Flags and Chestshop

### ISSUE THREAD

**Issue by Resi23** [IntellectualSites/PlotSquared#2358]
**Description of the problem:**
PlotSquared v4.286, Chestshop Dev Build #146, WorldEdit v7.0.0-SNAPSHOT;4271-405bf8d
Cant use Chestshop Signs. P2 say no use Permission. I try add "sign,wall_sign,oak_wall_sign,oak_sign,spruce_wall_sign,spruce_sign,birch_wall_sign,birch_sign,jungle_wall_sign,jungle_sign,acacia_wall_sign,acacia_sign,dark_oak_wall_sign,dark_oak_sign" to the use flags in world.yml. If i enter "/plot info" only ""sign,wall_sign" under the use flags

**How to replicate:** 
Try to use Cheshop Signs on Plots with new 1.14 Signs

**Comment by MattBDev** [comment]
Thanks for the report. I'll look into getting this fixed soon because I know a lot of players use chestshops with PlotSquared.

**Comment by AeSix** [comment]
It appears ChestShop hasn't been updated for 1.14... 
There is a an update, 147, which "always register WorldGuard shop flag" - which may have absolutely nothing to do with this issue.  

There is also https://ci.minebench.de/job/ChestShop-LegacyIds/  (again, not updated for 1.14, but maybe might help?)

**Comment by Resi23** [comment]
I have build 147 from chestshop and build 33 ChestShop LegacyIds it works great without p2.

**Comment by MattBDev** [comment]
I still need to add the new id's without breaking support for 1.13.2

**Comment by Resi23** [comment]
Could you possibly create a 1.14+ only version for the transition?

**Comment by MattBDev** [comment]
I thought about it but I decided it's not worth fragmenting the plotsquared versions any more.

**Comment by Resi23** [comment]
ok that I understand it would be synonymous only a transitional solution. I tried to get it myself, but I'm a beginner and can not handle it

**Comment by Resi23** [comment]
With the new Update i can use oak_sign but not oak_Wall_sign

**Comment by dordsor21** [comment]
Try the latest build. I think all signs should be working now?

**Comment by Resi23** [comment]
The same normal oak_sign works with chestshop. But the oak_wall_sign does not work. If the sign is so directly to the chest. Old numeric ID 68

**Comment by Resi23** [comment]
with build 295 The same normal oak_sign works with chestshop. But the oak_wall_sign does not work. If the sign is so directly to the chest. Old numeric ID 68
It is also not displayed under flags

`use: sign,wall_sign,oak_wall_sign,oak_sign,spruce_wall_sign,spruce_sign,birch_wall_sign,birch_sign,jungle_wall_sign,jungle_sign,acacia_wall_sign,acacia_sign,dark_oak_wall_sign,dark_oak_sign`


https://i.imgur.com/Yv8VXv4.png

**Comment by dordsor21** [comment]
Oh I pushed to the wrong branch try now https://ci.athion.net/job/PlotSquared-Breaking/296/ it'll take a while to build because of a route leak affecting a lot of services (read; https://www.cloudflarestatus.com/)

**Comment by Resi23** [comment]
Yes it Works nice thank you.

**Comment by NoFace851** [comment]
I'm sorry but this still doesn't work for me, i have set the use flag for 
sign,wall_sign,oak_wall_sign,oak_sign,spruce_wall_sign,spruce_sign,birch_wall_sign,birch_sign,jungle_wall_sign,jungle_sign,acacia_wall_sign,acacia_sign,dark_oak_wall_sign,dark_oak_sign

but i still get this message:

https://imgur.com/a/0qdKcop

world.yml: https://pastebin.com/gKNzuuNu
Plotsquared version:  PlotSquared (Version: PlotSquared-4.338)

**Comment by MattBDev** [comment]
@NoFace851 You seem to be having a lot of issues. maybe you should contact us on discord for help instead of commenting on all these old outdated issues.

**Comment by NoFace851** [comment]
sure, what's the discord?

**Comment by MattBDev** [comment]
@NoFace851 the link is literally **everywhere** but I'll post it for you again here. https://discord.gg/ngZCzbU
