### ISSUE TITLE
Changing the plot wall in worlds.yml has no effect

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#2398]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 4.291

**[REQUIRED] Spigot/Paper Version Number:** 1.14.2

**[REQUIRED] Minecraft Version Number:** 1.14.2

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** I've had to change the wall blocks for UNCLAIMED plots from air to slabs (because it was causing sign bugs when I used air). however I cant get the new wall appear or replace the old one. what I tried was using /p debugroadregen to see if it appears and from what I can see is that it does. so now I tried to use /p regenallroads but after hours of waiting, nothing happened. it even destroyed the CLAIMED slabs and replaced them with AIR. but when I claim an empty plot and delete it again <- this does appear my wanted wall. what am I doing wrong?

**Any relevant console output or screenshots:**

**Plugins being used on the server:**
ChatEx
DailyRewards
Essentials-X-2.16.1.183-mc114-b98
EssentialsXSpawn-2.16.1.0
images-1.0.6-SNAPSHOT
LeadTheWay
Multiverse-Core-3.0.0-SNAPSHOT
MyPet-3.2
PermissionsEx-1.23.4
PlaceholderAPI-2.10.2.jar
PlotSquared-Bukkit-4.291.jar
ProtocolLib.jar
RifleChairs.jar
Scoreboard-revision.jar
Vault.jar
WarpPortals-5.6.5-SNAPSHOT.jar
worldedit-bukkit-7.0.0-rc-2.jar
worldguard-legacy-7.0.0-rc-1.jar

**How to replicate:** 
1. change worlds.yml (wall: block - from "air:100" to "purpur_slab:100")
2. upload that file and use "/p reload" inworld
3. claim a plot, then /delete it again
4. you will now see the wanted wall. even if you use /p debugroadregen you can see it.
5. but you cant make them appear everywhere when using the /p regenallroads command

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
regen all roads. 
The command is in the wiki. 
That should fix the walls.

If it don't, or you had additional problems, please jump in the discord and ask.

**Comment by AnimeDrache** [comment]
Greetings AeSix. Thank you very much for answering me so quickly. You helped me already once today. However I am in the Discord the second time now. My first question on 05-29-2019 was never answered there or my questions today. Thats why I tried Github. I thank you a lot for your answers. However I already used the regen all roads command and waited hours just to see that he didnt replace the unclaimed "air:100" wall blocks with "purpur_slab:100". instead of that, he did even remove all the claimed "quartz_slab:100" slabs and replaced them with air. I did that on the 4.287 version. trying it with the new 4.291 version now (but the regen all roads will take many more hours now). any ideas?

Oh and what I can see so far: http://prntscr.com/o2cbe9 - the regen all road process is still running and he replaced my claimed "quartz_slab" with the "purpur_slab" which shouldnt happen. it should happen to UNCLAIMED plots. plus as you can see, he changed it only on the half megaplot.

**Comment by alexschrod** [comment]
There is a problem with road regeneration that I fixed in a pull request #2383 that hasn't been accepted yet, but once (if?) that is incorporated into the code, road regeneration should work correctly.

**Comment by MattBDev** [comment]
@alexschrod I knew I forgot something!

**Comment by DKKitty** [comment]
not sure if 4.292 was supposed to fix this but im still having this exact issue

**Comment by alexschrod** [comment]
@DKKitty and you let the regenallroads finish completely? Fixing up the walls is the very last thing it does, so you wouldn't see it working until it's completely done.

If you want to test if it's working or not without having to wait for the whole plot world to regenerate its roads, try running `/plot debugroadregen region` which will only regen the roads within the region you are standing.

**Comment by DKKitty** [comment]
yes ive run it multiple times. when the plot is claimed it still makes it sandstone slabs and when deleted reverts to the stone slabs. Thing is, whenever the plugin loads the data for that world its loading the wrong thing, as if it is loading a "default" setup
what console says:
![p2badloaderror](https://user-images.githubusercontent.com/45343169/59950767-cee5f080-946e-11e9-93e8-1498fb6fa138.PNG)

what the worlds file says:
![p2config](https://user-images.githubusercontent.com/45343169/59950845-17051300-946f-11e9-87d9-d595a8ae3cc5.PNG)

the road schematic is in place and working, and i can generate a new world fine with the same schematicsbut the on claimed and non claimed just will not work for me

**Comment by alexschrod** [comment]
That's odd. I tried changing the `block_claimed` in one of my worlds, and it works as expected. Hard to fix an issue you can't reproduce.

**Comment by Kalamityy** [comment]
its really odd, i cant change it any of my p2 worlds, it still uses sandstone slab and stone slab, even in the world i created specifically to test this.
no matter what I do console still shows the default slabs when booting p2, is there any advice or assistance you could offer? ll take any help i can get at this point im tired of making new worlds and running regenallroads just to get the same results each time xD

would it be helpful if i created a new ticket with all my server info ?

**Comment by Kalamityy** [comment]
updated to 4.297 and the issue is no longer there thanks guys :)
