### ISSUE TITLE
Merged plots visit different than v5

### ISSUE THREAD

**Issue by crafter23456** [IntellectualSites/PlotSquared#3143]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

You can only teleport to one of two owner of the plots and not both.

### To Reproduce

1. Merge a plot with different owner, that a plot has two owner
2. /p i 
3. Try to /p v to the second owner
4. Found no plots in your search query
I thought in v5 that I can teleport to the merged plot with both of the owner in /p v. 

### Expected behaviour

That I can teleport with both names to the merged plots like in v5 because the player has a plot, but the message says he doesnt have one.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2a586f634a814e319d96771bfb492ec8

### PlotSquared Version

6.0.5 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TNTUP** [comment]
Can confirm this, got several reports. 2 player-merged plots, if there's 2 owners only the first can be /plot visit name

**Comment by dordsor21** [comment]
Fixed in a8fc6662e05bbc36cd3b08f0539cc93e4d0a7ee0

**Comment by TNTUP** [comment]
Still persists as of 6.1.1 getting "Found no plots with your search query" by typing /plot visit WikiPiimp as expected should teleport either owner to this plot

![oof](https://i.qcfb.ca/20210912185048.png)

**Comment by TNTUP** [comment]
Any news? Got a player report about he/shecouldn't visit his/her plot which is merged (two owners)
