### ISSUE TITLE
Error with permissions and flags

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#618]
You removed the spectator flag from the permpacks, however it can still be set using /plot flag add

This is the relevant permissions nodes for players
        - plots.set.alias
        - plots.visit.other
        - plots.plot.1
        - plots.merge.1
        - plots.permpack.basicinbox
        - plots.permpack.basicflags
        - plots.permpack.basic

/plot flag set gamemode spectator
https://gyazo.com/33c88561a62511df3cf0db03862e026c

/plot flag add gamemode spectator
https://gyazo.com/689b0f2512de3b2d36b4da5386a21bf5

ALSO

players can do 
/plot flag set
 ... but not:
/plot set flag
which seems kinda strange

**Comment by boy0001** [comment]
Should be fixed. They both now forward to the same command.

**Comment by PhanaticD** [comment]
this is not fixed, "/plot flag add gamemode spectator" still adds the flag

**Comment by boy0001** [comment]
Can't seem to replicate, can you send me a dump of your permissions?

**Comment by PhanaticD** [comment]
I listed in the first post the plotsquared permissions nodes I have given
