### ISSUE TITLE
Plot swapping not respecting Biomes and Hanging Entities

### ISSUE THREAD

**Issue by ravand1990** [IntellectualSites/PlotSquared#708]
Spigot Version: 1627 (1.7.10)
P² Version: 3.1.9

When swapping two plots, neither the biomes nor the hanging entities are kept.

The hanging entities on both plots simply get cleared and no new hanging entities get created.
Whats not working: ItemFreams,Paintings and Leashes
Biomes just remain on the previous plots and also do not get moved with the blocks.

Here a stacktrace for trying to restore hanging entities: http://hastebin.com/ojewuziyoq.avrasm

Living Entities, Arrows, Boats, Minecarts on the otherhand get swapped perfectly fine, so im guessing there is something wrong while trying to restore previous hanging entities?

According to Empire92 entities swapping works in 1.8 but biome swapping doesn't. Maybe the way to create Hanging entities in 1.8 changed?

**Comment by MattBDev** [comment]
This should be fixed now.

**Comment by boy0001** [comment]
Not fixed. Hangings / biomes are not handled properly in 1.7.10

**Comment by ravand1990** [comment]
Oh noo :( and i was looking forward to update today, you have to fix it now :D! I'm waiting since ages for this to get fixed

**Comment by ravand1990** [comment]
So what about this issue now? Any realistic chance that it's going to be fixed?

**Comment by manuelgu** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1014

**Comment by boy0001** [comment]
Installing FAWE (https://www.spigotmc.org/resources/13932/) uses a bunch of NMS to handle hangings etc, which might fix it for PlotSquared.

**Comment by ravand1990** [comment]
Can anyone confirm if FAWE fixes this issue? Using AWE atm can't really switch atm and don't have any testing environments
