### ISSUE TITLE
Plot Border Change still not working right

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#810]
![2015-12-27_19 54 59](https://cloud.githubusercontent.com/assets/10485646/12011773/d97e8ccc-acd3-11e5-87b9-c1c3678fff64.png)
The stone slab is the default in the config and the nether slab is there because I set it as the border with /plot set border however it shows nether and stone slabs, I found out that by relogging the slabs are all set to whatever was defined in the /plot set border command. The bigger issue I'm getting is that  some chunks appear missing after executing the border command and I even encountered this issue when clearing a plot. I'm using version: 3.2.24 the one which was uploaded december 16th.

Config file: http://pastebin.com/it7gVWYv

**Comment by SecretlyJealous** [comment]
The only way to get rid of the missing chunk is to right click on it and it turns back to normal.

**Comment by boy0001** [comment]
Config looks fine. Are you using bukkit 1.7.10 or older?

**Comment by Andre601** [comment]
I have the same problem...
If you use Multiverse you need to leave the world and reload MV.
After that everything should be fine,,,

**Comment by SecretlyJealous** [comment]
I'm using spigot 1.8.8, I don't use multiverse either.

**Comment by CoolLord22** [comment]
This has happened to me as well, and I found the best thing to do is select 2 corners where you can build (with worldedit) and do //expand vert, then do //regen. It gets rid of the chunk error.

**Comment by Sauilitired** [comment]
@CoolLord22 Just moving to another world, and back, should fix it too. Or simply relogging.

**Comment by CoolLord22** [comment]
I tried had relogging but it didn't seem to fix it. But, I haven't seen this issue in a bit so maybe the results are different now. Thanks for letting me know!

**Comment by Andre601** [comment]
Sometimes it works with simply relogging or tp to another world...
But sometimes not and one of the best ways is zo reload Multiverse...

**Comment by CoolLord22** [comment]
@Andre601 Ah okay. Thanks to you too! :)

**Comment by chamunks** [comment]
I'm closing this ticket since it's over six months with no activity.  If you're still experiencing this issue please feel free to comment / reopen the issue with more information so we can attempt to replicate your issue in our testing environment. 

When/if you re-open this issue please be sure to provide a /plot debugpaste in your response so that we can confirm and fix the issue faster. 

Things that can help solve your problems include upgrading all of your plugins to the latest possible version that your setup can handle as we generally don't fix backdated versions.

Be sure to follow this issue [reporting guideline.](https://github.com/IntellectualSites/PlotSquared/blob/master/.github/ISSUE_TEMPLATE.md)
