### ISSUE TITLE
Server crash on clear/delete plot [SEVERE All server with PS can be crashed]

### ISSUE THREAD

**Issue by SpyL1nk** [IntellectualSites/PlotSquared#997]
Crash report of the server: http://pastebin.com/32PNK3mY

Our server crash when someone clear or delete a plot which contains a daylight detector. I tested on other servers and this issue can be easily replicated by anyone ... I tested many versions of PlotSquared and version 3.2.26 from Jan 12, 2016 is good but all 3.3.X I downloaded (from Bukkit, Spigot, your Jenkins) are bugged ...

How to replicate: simply place a daylight detector on a plot (claimed or not) and other blocks or only the detector and delete it (if claimed) or clear it. It will clear the plot and then crash the server ...

This issue happen in 1.8.X and 1.9 and with ViaVersion, so I'm not sure it's a Minecraft issue ...

**Comment by manuelgu** [comment]
This has been reported to the Spigot JIRA and can be found [here](https://hub.spigotmc.org/jira/browse/SPIGOT-575).

**Comment by SpyL1nk** [comment]
"This was caused by a plugin and has since been fixed in that plugin, please close"
This was the reported comment so I think it's a plugin issue and this was reported in Mar 2015, more than a year ago.

**Comment by fabien91** [comment]
I can confirm this, it's a severe bug that cause crash total of server...
And i've test with no plugin and just add PlotSquared on test server the bug is still present.

**Comment by MattBDev** [comment]
can you provide your latest.log file too? It may provide some more helpful information. Preferably using www.hastebin.com (I hate pastebin)

**Comment by SpyL1nk** [comment]
This is a log file of a test in 1.8.8, but the error is the same in 1.9: http://www.hastebin.com/huyiduriji.sm

**Comment by MattBDev** [comment]
@SpyL1nk do you have fastmode clear enabled?

**Comment by SpyL1nk** [comment]
No, fastmode is defined on false on the server.

**Comment by SpyL1nk** [comment]
I just tested with the fastmode enabled and it seems that it works. I will enable this to correct until you can patch it (or not).
